import scrapy
from scrapy.linkextractors import LinkExtractor
from scrapy.spiders import CrawlSpider, Rule
from scrapy_playwright.page import PageMethod

class MoittPakistanSpider(CrawlSpider):
    """
    SPIDER: Pakistan MoITT AI Policies & Islamabad Declaration
    
    This spider targets the official Ministry of IT & Telecom portal.
    Government portals frequently update URL structures for announcements 
    and policies. To ensure robust tracking of the Cabinet-approved National 
    AI Policy, AI Regulatory Directorate compliance rules, and the Islamabad 
    AI Declaration, this spider implements rigorous link-following logic.

    It uses scrapy-playwright to ensure any dynamically loaded React/Angular 
    announcement lists are fully rendered before links are extracted.
    """
    name = "moitt_pakistan"
    allowed_domains = ["moitt.gov.pk"]
    
    # Start at the primary policy and announcements hubs
    start_urls = [
        "https://moitt.gov.pk/Policies",
        "https://moitt.gov.pk/NewsAndEvents",
        "https://moitt.gov.pk/"
    ]

    # Implement rigorous link-following logic
    # We want to follow links that might contain our target keywords in the URL or text
    rules = (
        Rule(
            LinkExtractor(
                allow=(r'/Detail/', r'/Policy/', r'/News/'),
                deny=(r'/ContactUs', r'/AboutUs', r'/Tenders')
            ), 
            callback='parse_policy_page', 
            follow=True,
            # Pass Playwright meta to ensure followed links are also rendered via the headless browser
            process_request='use_playwright'
        ),
    )

    def use_playwright(self, request, response):
        """
        Middleware hook to inject Playwright parameters into requests 
        generated by the CrawlSpider's LinkExtractor.
        """
        request.meta['playwright'] = True
        # Wait for the main post/entry content area to load
        request.meta['playwright_page_methods'] = [
            PageMethod("add_init_script", script="Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"),
            PageMethod("wait_for_selector", "div.post-content, div.entry-content, article, div#content", timeout=20000)
        ]
        return request

    def start_requests(self):
        """
        Override start_requests to ensure the initial URLs are loaded via Playwright.
        """
        for url in self.start_urls:
            yield scrapy.Request(
                url,
                meta={
                    "playwright": True,
                    "playwright_page_methods": [
                        PageMethod("add_init_script", script="Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"),
                        PageMethod("wait_for_load_state", "networkidle")
                    ],
                }
            )

    def parse_policy_page(self, response):
        """
        Extracts the text body from individual policy or announcement pages.
        Filters out irrelevant pages by searching for key terms.
        """
        # Extract all text from the main content container
        content_div = (
            response.css("div.post-content") or 
            response.css("div.entry-content") or 
            response.css("article") or 
            response.css("div#content")
        )

        if content_div:
            raw_text = "\n\n".join(content_div.css("::text").getall())
        else:
            raw_text = "\n\n".join(response.css("body ::text").getall())

        raw_text_lower = raw_text.lower()
        url_lower = response.url.lower()

        # Targeting specific compliance rules: AI Policy, Islamabad AI Declaration, 
        # Regulatory Directorate, Risk classifications, Sovereign cloud.
        target_keywords = [
            "artificial intelligence", "ai policy", "islamabad ai declaration",
            "ai regulatory directorate", "risk classification", "sovereign cloud",
            "data residency"
        ]

        # Check if the page is relevant to our legal mapping
        is_relevant = any(keyword in raw_text_lower or keyword in url_lower for keyword in target_keywords)

        if is_relevant and raw_text.strip():
            self.logger.info(f"Target Policy Match Found: {response.url}")
            
            # Stream the extracted data element into the 'LegalCloudRoutingPipeline' engine
            yield {
                "jurisdiction": "Pakistan",
                "sub_jurisdiction": "Federal",
                "document_type": "Policy",
                "source_url": response.url,
                "raw_text": raw_text
            }
        else:
            self.logger.debug(f"Page skipped (no target AI keywords found): {response.url}")
